# Generated by Django 3.1.3 on 2021-09-22 13:49

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_jisu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_jisu',
                'managed': False,
            },
        ),
    ]
