# Generated by Django 3.1.3 on 2021-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_Kospi200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_kospi200',
                'managed': False,
            },
        ),
    ]
