# Generated by Django 3.1.3 on 2021-09-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0004_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
