# Generated by Django 3.1.3 on 2021-10-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0006_stock_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_info',
            options={'managed': False},
        ),
    ]
