# Generated by Django 3.1.3 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0007_auto_20211002_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('code_name', models.TextField(blank=True, null=True)),
                ('code_num', models.IntegerField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('volumn', models.BigIntegerField(blank=True, null=True)),
                ('ma20', models.FloatField(blank=True, null=True)),
                ('stddev', models.FloatField(blank=True, null=True)),
                ('upper_b', models.FloatField(blank=True, null=True)),
                ('lower_b', models.FloatField(blank=True, null=True)),
                ('percent_b', models.FloatField(blank=True, null=True)),
                ('bandwidth', models.FloatField(blank=True, null=True)),
                ('macd_short', models.FloatField(blank=True, null=True)),
                ('macd_long', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('trading_volume', models.BigIntegerField(blank=True, null=True)),
                ('out_share', models.BigIntegerField(blank=True, null=True)),
                ('ins_buy', models.FloatField(blank=True, null=True)),
                ('for_buy', models.FloatField(blank=True, null=True)),
                ('ins_sell', models.FloatField(blank=True, null=True)),
                ('for_sell', models.FloatField(blank=True, null=True)),
                ('au', models.FloatField(blank=True, null=True)),
                ('ad', models.FloatField(blank=True, null=True)),
                ('rs', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_interaction',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='stock_info',
            table='stock_info',
        ),
    ]
