# Generated by Django 3.1.3 on 2021-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0008_auto_20211002_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='kospi200_list',
            fields=[
                ('code_name', models.TextField(blank=True, null=True)),
                ('close', models.TextField(blank=True, null=True)),
                ('diff', models.TextField(blank=True, null=True)),
                ('per', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('market_cap', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kospi200_list',
                'managed': False,
            },
        ),
    ]
