# Generated by Django 3.1.3 on 2021-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juju', '0009_kospi200_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('profit_a', models.FloatField(blank=True, null=True)),
                ('ni', models.FloatField(blank=True, db_column='Ni', null=True)),
                ('ni_sh', models.FloatField(blank=True, db_column='Ni_sh', null=True)),
                ('ni_nsh', models.FloatField(blank=True, db_column='Ni_nsh', null=True)),
                ('ta', models.FloatField(blank=True, db_column='TA', null=True)),
                ('td', models.FloatField(blank=True, db_column='TD', null=True)),
                ('te', models.FloatField(blank=True, db_column='TE', null=True)),
                ('con_sh', models.FloatField(blank=True, null=True)),
                ('con_nsh', models.FloatField(blank=True, null=True)),
                ('cap', models.FloatField(blank=True, null=True)),
                ('debt_r', models.FloatField(blank=True, null=True)),
                ('reten_r', models.FloatField(blank=True, null=True)),
                ('margin_r', models.FloatField(blank=True, null=True)),
                ('profit_sh', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, db_column='ROA', null=True)),
                ('roe', models.FloatField(blank=True, db_column='ROE', null=True)),
                ('eps', models.FloatField(blank=True, db_column='EPS', null=True)),
                ('bps', models.FloatField(blank=True, db_column='BPS', null=True)),
                ('dps', models.FloatField(blank=True, db_column='DPS', null=True)),
                ('per', models.FloatField(blank=True, db_column='PER', null=True)),
                ('pbr', models.FloatField(blank=True, db_column='PBR', null=True)),
                ('num_sh', models.FloatField(blank=True, db_column='Num_sh', null=True)),
                ('div_income', models.FloatField(blank=True, db_column='Div_income', null=True)),
                ('code_num', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'f_summary',
                'managed': False,
            },
        ),
    ]
